---
- name: Configure NFS Server
  hosts: nfs
  become: true

  tasks:

    - name: Install NFS utilities
      dnf:
        name: nfs-utils
        state: present

    - name: Create NFS export directory
      file:
        path: /srv/nfs/k8s
        state: directory
        owner: nobody
        group: nobody
        mode: "0777"

    - name: Configure exports
      copy:
        dest: /etc/exports
        content: |
          /srv/nfs/k8s 172.31.0.0/16(rw,sync,no_subtree_check,no_root_squash)

    - name: Enable and start NFS server
      systemd:
        name: nfs-server
        enabled: true
        state: started

    - name: Export NFS shares
      command: exportfs -rav