[k8s]
k8s-cp1 ansible_host=18.184.101.133
k8s-w1 ansible_host=35.159.225.67
k8s-w2 ansible_host=3.123.22.229

[nfs]
nfs-srv ansible_host=63.176.97.115

[gitlab]
gitlab-srv ansible_host=3.67.91.250

[k8s:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=../terraform/k8s-assignment-key.pem
ansible_python_interpreter=/usr/bin/python3

[nfs:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=../terraform/k8s-assignment-key.pem
ansible_python_interpreter=/usr/bin/python3

[gitlab:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=../terraform/k8s-assignment-key.pem
ansible_python_interpreter=/usr/bin/python3
